import { ThemeProvider } from '@/components/providers/ThemeProvider'
import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react'
import QueryClientWrapper from '@/components/providers/QueryClientWrapper'
import SessionProviderWrapper from '@/components/providers/SessionProviderWrapper'
import { getServerSession } from 'next-auth'
import { authOptions } from './lib/auth/firebase'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviderWrapper session={session!}>
          <QueryClientWrapper>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
            >
              {children}
            </ThemeProvider>
          </QueryClientWrapper>
        </SessionProviderWrapper>
      </body>
    </html>
  )
}
