import { ThemeProvider } from '@/components/providers/ThemeProvider'
import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react'
import QueryClientWrapper from '@/components/providers/QueryClientWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientWrapper>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
            {children}
          </ThemeProvider>
        </QueryClientWrapper>
      </body>
    </html>
  )
}
